server.port=8083

spring.application.name=offer-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/offerDB}
spring.datasource.username=${DB_USER:jacobo}
spring.datasource.password=${DB_PASSWORD:jacobo123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://znyracho:6OWkLPKTK6ayX4_Kc7ayjS2KeVROhj0d@moose.rmq.cloudamqp.com/znyracho}

# Exchange y Queue names
rabbitmq.exchange=mindbridge.exchange
rabbitmq.routing-key.offer-created=offer.created
rabbitmq.routing-key.offer-cancelled=offer.cancelled
rabbitmq.routing-key.offer-taken=offer.taken