server.port=8083

spring.application.name=offer-service

spring.datasource.url=jdbc:postgresql://localhost:5432/offerDB
spring.datasource.username=jacobo
spring.datasource.password=jacobo123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework=DEBUG